src/LesVoorbeeldAttributeRouting/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyHowest;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace LesVoorbeeldAttributeRouting.Controllers
{
    public class HomeController : Controller
    {
        private string[] groenten;

        public HomeController()
        {
            groenten = new string[] { "Rode kool", "Bloemkool", "Sla", "Komkommer" };
        }

        public string Hello(string name) => $"Hallo {name}!!!";

        public IActionResult Index()
        {
            ViewBag.message = (DateTime.Now.Hour < 12) ? "Goedemorgen" : "Goedemiddag";
            return View();
        }

        public IActionResult Groenten(string zoekGroente)
        {
            ViewBag.groenten = groenten;
            if (!string.IsNullOrEmpty(zoekGroente))
                    ViewBag.zoekResultaat = $"De groente {zoekGroente} is de {Array.IndexOf(groenten, zoekGroente) +1}e groente in de lijst ";
            return View();
        }


        public IActionResult Student()
        {
            Student howestStudent = new MyHowest.Student()
                { Id=345, Naam="Jason Page", Afstudeergraad=Graad.Voldoende };

            List<Student> studenten = new List<MyHowest.Student>();
            studenten.Add(new MyHowest.Student() { Id=444, Naam="Karen Desmet", Afstudeergraad=Graad.Onderscheiding });
            studenten.Add(howestStudent);

            ViewBag.studenten = studenten;
            return View();
        }

        public IActionResult GroentenJSON()
        {
            return Json(groenten);
        }

    }
}

src/LesVoorbeeldAttributeRouting/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace LesVoorbeeldAttributeRouting.Controllers
{
    [Route("")]
    public class StudentController : Controller
    {
        [Route("")]
        [Route("Student/Index/{naam:length(3,15)}/{leeftijd:int:min(18)}")]
        public IActionResult Index(string naam, int leeftijd=0)
        {
            if (!string.IsNullOrEmpty(naam))
            {
                return  Content($"{naam} is {leeftijd} jaar oud");
            }
            return View();
        }

        [Route("[controller]/[action]")]
        public IActionResult Add()
        {
            return Content("Added");
        }

    }


}

src/LesVoorbeeldAttributeRouting/Views/Home/Groenten.cshtml
    <h2>Groenten</h2>
    <ul>
        @foreach (var groente in ViewBag.groenten)
        {
            <li>@groente</li>
        }
    </ul>
    @ViewBag.zoekResultaat

src/LesVoorbeeldAttributeRouting/Views/Home/Index.cshtml
    <h1>@ViewBag.message</h1>

    @Html.ActionLink("Ga naar Groenten","Groenten")

    @Html.ActionLink("Ga naar Studenten", "Student")

src/LesVoorbeeldAttributeRouting/Views/Home/Student.cshtml
    <h2>Studenten</h2>
    @foreach(var student in ViewBag.studenten)
        {
            <ul>
                <li>@student.Id</li>
                <li>@student.Naam</li>
                <li>@student.Afstudeergraad</li>
            </ul>
        }

src/LesVoorbeeldAttributeRouting/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LesVoorbeeldAttributeRouting</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">LesVoorbeeldAttributeRouting</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - LesVoorbeeldAttributeRouting</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/LesVoorbeeldAttributeRouting/Views/Student/Index.cshtml
<h2>Student welkom!!</h2>